[workspace]
resolver = "2"
members = [
    "dna/zomes/profiles",
    "dna/zomes/comments",
    "dna/zomes/reactions",
    "dna/zomes/lobby",
    "dna/zomes/topics",
    "dna/zomes/posts",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
